services:
  backend:
    build: ./mern/backend
    ports:
      - "5000:5000" 
    networks:
      - mern_network
    environment:
      MONGO_URI: mongodb://mongo:27017/mydatabase  
    depends_on:
      - mongodb
    hostname: My-file
    container_name: backend-container

  frontend:
    build: ./mern/frontend
    ports:
      - "5001:5001"  
    networks:
      - mern_network
    environment:
      REACT_APP_API_URL: http://backend:5000
    hostname: My-file
    container_name: frontend-container
  mongodb:
    image: mongo:latest  
    ports:
      - "27017:27017"  
    networks:
      - mern_network
    volumes:
      - mongo-data:/data/db  
    hostname: My-Mongodb
    container_name: Mongodb-container

networks:
  mern_network:
    driver: bridge 

volumes:
  mongo-data:
    driver: local  

